import { Dimensions, StyleSheet } from "react-native";
const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#ffffff',
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingTop: 48,
      paddingBottom: 16,
    },
    header: {
      marginTop:10,
      // marginBottom: 20,
      paddingHorizontal: 10,
    },
    logoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      // marginBottom: 12,
      justifyContent: 'space-between',
    },
    welcomeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
      paddingHorizontal: 30,
    },
    welcomeText: {
      fontSize: 24,
      fontWeight: '400',
      color: '#FFFFFF',
    },
    userName: {
      fontSize: 24,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    bellButton: {
      padding: 8,
    },
    bellIcon: {
      fontSize: 24,
    },
    balanceCardWrapper: {
      paddingHorizontal: 30,
    },
    balanceCard: {
      zIndex: 5,
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      padding: 24,
      marginBottom: -34,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    balanceLeft: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    balanceLabel: {
      fontSize: 20,
      fontWeight: '400',
      color: '#666666',
    },
    balanceValue: {
      fontSize: 20,
      fontWeight: '700',
      color: '#000000',
    },
    pointLabel: {
      fontSize: 12,
      fontWeight: '400',
      color: '#666666',
    },
    pointValue: {
      fontSize: 12,
      fontWeight: '700',
      color: '#55CB95',
      textAlign: 'right',
    },
    balanceActions: {
      flexDirection: 'row',
      gap: 7,
    },
    actionButton: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 42,
    },
    actionIconWrap: {
      marginBottom: 4,
    },
    actionLabel: {
      fontSize: 10,
      color: '#000000',
      fontWeight: '400',
    },
    section: {
      marginBottom: 24,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
      paddingHorizontal: 20,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#000000',
    },
    lihatSemua: {
      fontSize: 14,
      color: '#666666',
    },
    horizontalList: {
      paddingRight: 20,
    },
    tailorCard: {
      width: 140,
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      padding: 12,
      alignItems: 'center',
      marginRight: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    avatarWrapper: {
      position: 'relative',
      marginBottom: 8,
    },
    avatarPlaceholder: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: '#E0E0E0',
      borderWidth: 3,
      borderColor: '#D4AF37',
    },
    verifiedBadge: {
      position: 'absolute',
      top: -2,
      right: -2,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: '#190152',
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkmark: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: 'bold',
    },
    tailorName: {
      fontSize: 13,
      fontWeight: '600',
      color: '#000000',
      textAlign: 'center',
      marginBottom: 6,
    },
    tailorMeta: {
      alignItems: 'center',
    },
    tailorMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 2,
    },
    star: {
      fontSize: 12,
      color: '#000000',
      marginBottom: 2,
    },
    orderCount: {
      fontSize: 11,
      color: '#666666',
    },
    featuredProductCard: {
      width: 160,
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      overflow: 'hidden',
      marginRight: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    featuredProductImage: {
      width: '100%',
      height: 160,
      backgroundColor: '#E0E0E0',
    },
    featuredProductName: {
      fontSize: 14,
      fontWeight: '600',
      color: '#000000',
      padding: 12,
      paddingBottom: 4,
    },
    featuredProductPrice: {
      fontSize: 14,
      fontWeight: '600',
      color: '#000000',
      paddingHorizontal: 12,
      paddingBottom: 12,
    },
    newsCard: {
      width: SCREEN_WIDTH * 0.6,
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      overflow: 'hidden',
      marginRight: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    newsImagePlaceholder: {
      width: '100%',
      height: 120,
      backgroundColor: '#E0E0E0',
    },
    newsTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: '#000000',
      padding: 12,
      paddingBottom: 4,
    },
    newsFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingBottom: 12,
    },
    newsTag: {
      backgroundColor: '#E0E0E0',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 4,
    },
    newsTagText: {
      fontSize: 11,
      color: '#666666',
    },
    newsTimeRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    newsTime: {
      fontSize: 11,
      color: '#666666',
    },
    bottomSpacer: {
      height: 24,
    },
    // My Order tab styles (match attached design)
    myOrderContainer: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    bgcontainerWrapper: {
      backgroundColor: '#FFB200',
      borderBottomRightRadius: 50,
      borderBottomLeftRadius: 50,
    },
    myOrderHeaderBg: {
      backgroundColor: '#FFB200',
      borderBottomLeftRadius: 28,
      borderBottomRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 78,
    },
    myOrderHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 24,
    },
    myOrderBackBtn: {
      padding: 8,
      minWidth: 40,
    },
    myOrderBackIcon: {
      fontSize: 24,
      color: '#2E1065',
    },
    myOrderTitle: {
      fontSize: 19,
      fontWeight: '600',
      color: '#ffffff',
    },
    myOrderHeaderRight: {
      width: 40,
    },
    myOrderStepperRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      position: 'relative',
      paddingHorizontal: 12,
    },
    myOrderStepperLine: {
      position: 'absolute',
      left: 20,
      right: 20,
      height: 3,
      backgroundColor: '#ffffff',
      top: 11,
    },
    myOrderStepDot: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#ffffff',
      borderWidth: 6,
      borderColor: '#ffffff',
      zIndex: 1,
    },
    myOrderStepDone: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    myOrderStepCheck: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: 'bold',
      lineHeight: 12,
    },
    myOrderScroll: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    myOrderScrollContent: {
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 24,
    },
    myOrderRowWrap: {
      flexDirection: 'row',
      alignItems: 'stretch',
      marginBottom: 14,
    },
    myOrderCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 22,
      padding: 12,
      flex: 1,
      borderWidth: 1,
      borderColor: '#E8E8E8',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    myOrderImage: {
      width: 72,
      height: 72,
      borderRadius: 12,
      backgroundColor: '#E0E0E0',
      marginRight: 12,
    },
    myOrderInfo: {
      flex: 1,
    },
    myOrderItemName: {
      fontSize: 20,
      fontWeight: '700',
      color: '#000000',
      marginBottom: 4,
    },
    myOrderItemPrice: {
      fontSize: 15,
      fontWeight: '500',
      color: '#DB640F',
      marginBottom: 2,
    },
    myOrderItemEdit: {
      fontSize: 12,
      color: '#4B5563',
      fontWeight: '400',
    },
    myOrderQtyPillWrapper: {
      alignSelf: 'flex-end',
    },
    myOrderQtyPill: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 20,
      paddingHorizontal: 6,
      paddingVertical: 6,
      marginLeft: 8,
      backgroundColor: '#F59E0B',
    },
    myOrderQtyBtn: {
      width: 17,
      height: 17,
      borderRadius: 14,
      borderColor: '#000000',
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    myOrderQtyIcon: {
      fontSize: 18,
      fontWeight: '700',
      color: '#000000',
      paddingHorizontal: 4,
    },
    myOrderQtyText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#2E1065',
      minWidth: 20,
      textAlign: 'center',
      marginHorizontal: 4,
    },
    myOrderDeleteBtn: {
      width: 28,
      borderRadius: 18,
      marginLeft: 8,
      backgroundColor: '#FFB200',
      alignItems: 'center',
      justifyContent: 'center',
    },
    myOrderDeleteIcon: {
      color: '#FFFFFF',
      fontSize: 20,
    },
    myOrderDivider: {
      width: '80%',
      height: 1,
      backgroundColor: '#FFB200',
      alignSelf: 'center',
      marginTop: 10,
      marginBottom: 16,
    },
    myOrderTotalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 0,
      marginBottom: 18,
      paddingTop: 0,
      paddingHorizontal: 4,
    },
    myOrderTotalLabel: {
      fontSize: 16,
      fontWeight: '700',
      color: '#333333',
    },
    myOrderTotalValue: {
      fontSize: 16,
      fontWeight: '600',
      color: '#FFB200',
    },
    myOrderActionBtn: {
      backgroundColor: '#FFB200',
      borderRadius: 10,
      paddingVertical: 9,
      alignItems: 'center',
      justifyContent: 'center',
    },
    myOrderActionText: {
      color: '#FFFFFF',
      fontSize: 19,
      fontWeight: '700',
    },
    // Profile tab styles
    profileScroll: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    profileScrollContent: {
      paddingBottom: 24,
    },
    profileHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#FFB200',
      paddingHorizontal: 16,
      paddingTop: 48,
      paddingBottom: 16,
    },
    profileHeaderBack: {
      padding: 8,
    },
    profileHeaderBackIcon: {
      fontSize: 24,
      color: '#000000',
    },
    profileHeaderTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#000000',
    },
    profileHeaderBell: {
      padding: 8,
    },
    profileSection: {
      backgroundColor: '#FFB200',
      alignItems: 'center',
      paddingVertical: 24,
      paddingHorizontal: 24,
    },
    profileSectionWrapper: {
      marginBottom: -126,
      alignItems: 'center',
      justifyContent: 'center',
    },
    profileAvatarWrapper: {
      marginBottom: 12,
    },
    profileAvatar: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: '#E0E0E0',
    },
    editProfileButton: {
      backgroundColor: '#FFB200',
      borderRadius: 8,
      paddingVertical: 12,
      paddingHorizontal: 32,
    },
    editProfileButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
    },
    settingsSection: {
      marginTop: 116,
    },
    settingsBlock: {
      paddingHorizontal: 24,
      marginBottom: 16,
    },
    settingsBlockTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000000',
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    settingsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      paddingVertical: 14,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    settingsRowIconWrap: {
      marginRight: 12,
    },
    settingsRowLabel: {
      flex: 1,
      fontSize: 16,
      color: '#000000',
    },
    settingsRowArrow: {
      fontSize: 24,
      color: '#999999',
      fontWeight: '300',
    },
    profileBottomSpacer: {
      height: 24,
    },
    logoutRow: {
      backgroundColor: '#FFFFFF',
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 8,
    },
    logoutRowText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#B91C1C',
    },
    placeholderScreen: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
    },
    placeholderTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#000000',
      marginBottom: 8,
    },
    placeholderSubtitle: {
      fontSize: 16,
      color: '#666666',
      marginBottom: 24,
    },
    logoutButton: {
      backgroundColor: '#190152',
      borderRadius: 8,
      paddingVertical: 14,
      paddingHorizontal: 32,
    },
    logoutButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
    },
    bottomBar: {
      flexDirection: 'row',
      backgroundColor: '#FFFFFF',
      borderTopWidth: 1,
      borderTopColor: '#E0E0E0',
      paddingVertical: 12,
      paddingHorizontal: 24,
      justifyContent: 'space-around',
    },
    tabItem: {
      alignItems: 'center',
    },
    tabIconWrap: {
      marginBottom: 4,
    },
    tabIconWrapInactive: {
      opacity: 0.6,
    },
    tabLabel: {
      fontSize: 12,
      color: '#000000',
      opacity: 0.6,
    },
    tabLabelActive: {
      color: '#FFB200',
      fontWeight: '600',
      opacity: 1,
    },
  });